
# CFLAGS = -g -c -O3
# CC = g++
# TOOLS_FOLDER = ./tools
# BIN = ./bin


# main: HT.o main.o 

# main.o: main.C

# tempTable.o: tempTable.C

# # RUNS THE MAIN FILE
# run: main
# 	./main.exe

# # CLEANS ALL FILES IN DIRECTORY
# clean: 
# 	rm -f *.o *.exe